language: node_js

node_js:
  - "12.16.3"

cache:
  directories:
  - node_moudles

env:
  - CI=true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"
  - npm config set scripts-prepend-node-path true

script:
  - node -v
  - npm -v
  - yarn -v
  - echo "Testing Started ..."
  - yarn test
  - echo "Testing Finished."
